##---
# Source: splunk-kubernetes-metrics/templates/deploymentMetricsAggregator.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: splunk-kubernetes-metrics
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.0.1
    release: splunk-kubernetes-metrics
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk-kubernetes-metrics
      release: splunk-kubernetes-metrics
  template:
    metadata:
      labels:
        app: splunk-kubernetes-metrics
        release: splunk-kubernetes-metrics
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        checksum/config: 30fee7b2bae3574f71136f872cc8305d2cc0086aec00b30dab03913acf2f3830
    spec:
      serviceAccountName: splunk-kubernetes-metrics
      containers:
      - name: fluentd
        image: chaitanyaphalak/k8s-metrics-agg:beta-test-5
        imagePullPolicy: Always
        env:
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: splunk-kubernetes-metrics
                key: splunk_hec_token
        resources:
            limits:
              cpu: 200m
              memory: 300Mi
            requests:
              cpu: 200m
              memory: 300Mi

        volumeMounts:
          - name: conf-configmap
            mountPath: /fluentd/etc
          - name: secrets
            mountPath: /fluentd/etc/splunk
            readOnly: true
      volumes:
      - name: conf-configmap
        configMap:
          name: splunk-kubernetes-metrics-aggregator
      - name: secrets
        secret:
          secretName: splunk-kubernetes-metrics
