##---
# Source: splunk-kubernetes-metrics/templates/serviceAccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-kubernetes-metrics
  labels:
    app: splunk-kubernetes-metrics
    chart: splunk-kubernetes-metrics-1.0.1
    release: splunk-kubernetes-metrics
    heritage: Tiller
