# Default values for splunk-kubernetes-logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# logLevel is to set log level of the Splunk log collector. Avaiable values are:
# * trace
# * debug
# * info
# * warn
# * error
logLevel: "info"

splunk:
  sourcetype: _json
  source: |-
    kubernetes.objects.{{ tag | split: '.' | last }}
  hec:
    # host: <required from user input>
    # token: <required from user input>
    protocol: "https"
    insecureSSL: true

image:
  tag: 0.0.3
  pullPolicy: IfNotPresent

resources:
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  requests:
   cpu: 100m
   memory: 200Mi

nodeSelector: {}

tolerations: []

affinity: {}
