---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    version: 1.0.0


---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    version: 1.0.0
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - namespaces
  - nodes
  verbs:
  - get
  - list
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - watch


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    version: 1.0.0
roleRef:
  kind: ClusterRole
  name: splunk-kubernetes-objects
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: splunk-kubernetes-objects
  namespace: default


---
apiVersion: v1
kind: Secret
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    version: 1.0.0
type: Opaque
data:
  splunk_hec_token: MmY3ZWE3N2MtZmYzMC00NmY3LTg2MzYtZjk2Mjk2YTRkYTI0


---
map[name:pods]apiVersion: v1
kind: ConfigMap
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    version: 1.0.0
data:
  fluent.conf: |
    <system>
      log_level info
    </system>

    <source>
      @type kubernetes_objects
      tag kube.objects.*
      insecure_ssl true
      <pull>
        resource_name pods
      </pull>
      <pull>
        resource_name namespaces
      </pull>
      <pull>
        resource_name nodes
      </pull>
      <watch>
        resource_name events
      </watch>
    </source>

    <filter kube.**>
      @type jq_transformer
      # in ruby '\\' will escape and become just '\', since we need two '\' in the `gsub` jq filter, it becomes '\\\\'.
      jq '.record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\\\."; ":")) | .record'
    </filter>

    <match kube.**>
      @type splunk_hec
      protocol https
      hec_host 34.196.173.154
      hec_port 8088
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['SPLUNK_HEC_HOST']}"
      source_key source
      sourcetype_key sourcetype
      index demo-events
      insecure_ssl true
      <buffer>
        @type memory
        chunk_limit_size 200m
        chunk_limit_records 10000
        flush_interval 3s
        retry_max_times 3
      </buffer>
    </match>


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: splunk-kubernetes-objects
  labels:
    app: splunk-kubernetes-objects
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: splunk-kubernetes-objects
      engine: fluentd
      version: 1.0.0
  replicas: 1
  template:
    metadata:
      labels:
        app: splunk-kubernetes-objects
        engine: fluentd
        version: 1.0.0
      annotations:
        checksum/config: 5afd9b9519bfb166cb14447ea31b6792d03e93ad3282726f3368041697e31e4b
        checksum/helpers: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      serviceAccountName: splunk-kubernetes-objects
      terminationGracePeriodSeconds: 30
      containers:
      - name: splunk-fluentd-k8s-objects
        image: gimil/k8s-o:0.1.2
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: SPLUNK_HEC_HOST
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SPLUNK_HEC_TOKEN
          valueFrom:
            secretKeyRef:
              name: splunk-kubernetes-objects
              key: splunk_hec_token
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: conf-configmap
          mountPath: "/fluentd/etc"
        - name: secrets
          mountPath: "/fluentd/etc/splunk"
          readOnly: true
      volumes:
      - name: conf-configmap
        configMap:
          name: splunk-kubernetes-objects
      - name: secrets
        secret:
          secretName: splunk-kubernetes-objects
