apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "splunk-kubernetes-metrics.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-metrics.name" . }}
    chart: {{ template "splunk-kubernetes-metrics.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    k8s-app: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "splunk-kubernetes-metrics.name" . }}
      release: {{ .Release.Name }}
      k8s-app: heapster
  template:
    metadata:
      labels:
        app: {{ template "splunk-kubernetes-metrics.name" . }}
        release: {{ .Release.Name }}
        k8s-app: heapster
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      serviceAccountName: {{ template "splunk-kubernetes-metrics.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
        - image: k8s.gcr.io/heapster-amd64:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: heapster
          command:
            - /heapster
            - --source=kubernetes
            - --sink=log
            # - --source=kubernetes.summary_api:''
            - --sink=statsd:udp://127.0.0.1:5160
            # - --sink=statsd:udp://
            #   {{- required "splunk.udp.host is required" (or .Values.splunk.udp.host .Values.global.splunk.udp.host) -}}
            #   :
            #   {{- required "splunk.udp.port is required" (or .Values.splunk.udp.port .Values.global.splunk.udp.port) }}?numMetricsPerMsg=2
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.service.targetPort }}
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
          resources:
{{ toYaml .Values.resources | indent 12 }}
        - name: fluentd-splunk-forwarder
          image: gimil/k8s-l:0.0.4
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - fluentd
          args:
            - -c
            - /fluentd/etc/fluent.conf
          volumeMounts:
          - name: conf-configmap
            mountPath: /fluentd/etc
      volumes:
      - name: conf-configmap
        configMap:
          name: {{ template "splunk-kubernetes-metrics.fullname" . }}
