apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-kubernetes-objects.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-objects.name" . }}
    chart: {{ template "splunk-kubernetes-objects.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
    <system>
      log_level {{ .Values.logLevel }}
    </system>

    <source>
      @type kubernetes_objects
      insecure_ssl {{ .Values.splunk.hec.insecureSSL }}
      <pull>
        resource_name namespaces
      </pull>
      <pull>
        resource_name nodes
      </pull>
      <pull>
        resource_name pods
      </pull>
      <watch>
        resource_name events
      </watch>
    </source>

    <match kubernetes.**>
      @type splunk_hec
      hec_host {{ required "splunk.hec.host is required." .Values.splunk.hec.host }}
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      {{ if .Values.splunk.index }}index {{ .Values.splunk.index }}{{ end }}
      {{ if .Values.splunk.source }}source {{ .Values.splunk.source }}{{ end }}
      {{ if .Values.splunk.sourcetype }}sourcetype {{ .Values.splunk.sourcetype }}{{ end }}
      <ssl>
        insecure {{ .Values.splunk.hec.insecureSSL }}
      </ssl>
      <buffer>
        @type memory
        chunk_limit_size 10m
        chunk_limit_records 100
        flush_interval 3s
        retry_max_times 3
      </buffer>
    </match>
