apiVersion: v1
kind: Secret
metadata:
  name: {{ template "splunk-kubernetes-objects.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-objects.name" . }}
    chart: {{ template "splunk-kubernetes-objects.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  splunk_hec_token: {{ required "splunk.hec.token is required" .Values.splunk.hec.token | b64enc }}
