apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-kubernetes-logging.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-logging.name" . }}
    chart: {{ template "splunk-kubernetes-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
    # system wide configurations
    <system>
      log_level {{ .Values.logLevel }}
    </system>

    # reading kubelet logs from journal
    <source>
      @type systemd
      tag journal.kubelet
      filters [{ "_SYSTEMD_UNIT": "kubelet.service" }]
      path  {{ .Values.journalLogPath | default "/run/log/journal" | quote }}
      read_from_head true
      pos_file /var/log/fluentd-journald-kubelet.pos
    </source>

    # reading container logs from filesystem
    <source>
      @type tail
      tag tail.containers
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      path_key _file_path
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      format json
      read_from_head true
    </source>

    # ignore fluentd's log
    <match fluent.**>
      @type null
    </match>

    <match journal.**>
      @type splunk_hec
      hec_host {{ required "splunk.hec.host is required." .Values.splunk.hec.host }}
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['SPLUNK_HEC_HOST']}"
      source "kubernetes.{{ "{{" }} tag | split: '.' | last {{ "}}" }}"
      {{ if .Values.splunk.index }}index {{ .Values.splunk.index }}{{ end }}
      <ssl>
        insecure {{ .Values.splunk.hec.insecureSSL }}
      </ssl>
      <buffer>
        @type memory
        chunk_limit_size 500m
        chunk_limit_records 512000
        flush_interval 5s
        flush_thread_count 1
        overflow_action block
        retry_max_times 3
      </buffer>
    </match>

    <match tail.**>
      @type splunk_hec
      hec_host {{ required "splunk.hec.host is required." .Values.splunk.hec.host }}
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['SPLUNK_HEC_HOST']}"
      source "{{ "{{" }} record._file_path {{ "}}" }}"
      {{ if .Values.splunk.index }}index {{ .Values.splunk.index }}{{ end }}
      <ssl>
        insecure {{ .Values.splunk.hec.insecureSSL }}
      </ssl>
      <buffer>
        @type memory
        chunk_limit_size 500m
        chunk_limit_records 512000
        flush_interval 5s
        flush_thread_count 1
        overflow_action block
        retry_max_times 3
      </buffer>
      <format>
        @type single_value
        message_key log
        add_newline false
      </format>
    </match>
