apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "splunk-kubernetes-logging.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-logging.name" . }}
    chart: {{ template "splunk-kubernetes-logging.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    engine: fluentd
spec:
  template:
    metadata:
      labels:
        app: {{ template "splunk-kubernetes-logging.name" . }}
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      containers:
      - name: fluentd
        image: gimil/fluentd-splunk-hec:1.0.0-debian-alpha.2
        command:
          - fluentd
        args:
          - -c
          - /fluentd/etc/fluent.conf
        env:
          - name: SPLUNK_HEC_HOST
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SPLUNK_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ template "splunk-kubernetes-logging.fullname" . }}
                key: splunk_hec_token
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: conf-configmap
          mountPath: /fluentd/etc
        - name: varlog
          mountPath: /var/log
        - name: containerslog
          mountPath: /var/log/containers
          readOnly: true
        - name: podslog
          mountPath: /var/log/pods
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: runlogjournal
          mountPath: /run/log/journal
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: conf-configmap
        configMap:
          name: {{ template "splunk-kubernetes-logging.fullname" . }}
      - name: varlog
        hostPath:
          path: /var/log
      - name: containerslog
        hostPath:
          path: /var/log/containers
      - name: podslog
        hostPath:
          path: /var/log/pods
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: runlogjournal
        hostPath:
          path: /run/log/journal
