{{- required "Must have at least one object defined in `pullObjects` or `watchObjects`." (or (first .Values.pullObjects) (first .Values.watchObjects)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "splunk-kubernetes-objects.fullname" . }}
  labels:
    app: {{ template "splunk-kubernetes-objects.name" . }}
    chart: {{ template "splunk-kubernetes-objects.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  fluent.conf: |
    <system>
      log_level {{ or .Values.logLevel .Values.global.logLevel }}
    </system>

    <source>
      @type kubernetes_objects
      tag kube.objects.*
      insecure_ssl {{ .Values.kubernetes.insecureSSL }}
      {{- with .Values.kubernetes.secretDir }}
      secret_dir {{ . }}
      {{- end }}
      {{- if .Values.kubernetes.clientCert }}
      client_cert /fluentd/etc/splunk/k8s_client_cert
      {{- end }}
      {{- if .Values.kubernetes.clientKey }}
      client_key /fluentd/etc/splunk/k8s_client_key
      {{- end }}
      {{- if .Values.kubernetes.caFile }}
      ca_file /fluentd/etc/splunk/k8s_ca_file
      {{- end }}
      {{- with .Values.kubernetes.bearerTokenFile }}
      bearer_token_file {{ . }}
      {{- end }}
      {{- if .Values.checkpointFile.volume }}
      <storage>
        path /fluentd/var/checkpoints/{{ .Values.checkpointFile.name | default "kubernetes-objects" }}
      </storage> 
      {{- end }}
      {{- range $index, $object := .Values.pullObjects }}
      <pull>
        resource_name {{ required "name of the object to be pulled is required" $object.name }}
        {{- with $object.namespace }}namespace {{ . }}{{ end }}
        {{- with $object.labelSelector }}label_selector {{ . }}{{ end }}
        {{- with $object.fieldSelector }}field_selector {{ $object.fieldSelector }}{{ end }}
        {{- with $object.interval }}interval {{ $object.interval }}{{ end }}
      </pull>
      {{- end }}
      {{- range $index, $object := .Values.watchObjects }}
      <watch>
        resource_name {{ required "name of the object to be watched is required" $object.name }}
        {{- with $object.namespace }}namespace {{ . }}{{ end }}
        {{- with $object.labelSelector }}label_selector {{ . }}{{ end }}
        {{- with $object.fieldSelector }}field_selector {{ . }}{{ end }}
      </watch>
      {{- end }}
    </source>

    <filter kube.**>
      @type jq_transformer
      # in ruby '\\' will escape and become just '\', since we need two '\' in the `gsub` jq filter, it becomes '\\\\'.
      jq '.record.source = "namespace:\(env.MY_NAMESPACE)/pod:\(env.MY_POD_NAME)" | .record.sourcetype = (.tag | gsub("\\\\."; ":")) | .record'
    </filter>

    <match kube.**>
      @type splunk_hec
      protocol {{ or .Values.splunk.hec.protocol .Values.global.splunk.hec.protocol | default "https" }}
      hec_host {{ required "splunk.hec.host is required." (or .Values.splunk.hec.host .Values.global.splunk.hec.host) }}
      {{- with or .Values.splunk.hec.port .Values.global.splunk.hec.port }}
      hec_port {{ . }}
      {{- end }}
      hec_token "#{ENV['SPLUNK_HEC_TOKEN']}"
      host "#{ENV['SPLUNK_HEC_HOST']}"
      source_key source
      sourcetype_key sourcetype
      {{- with or .Values.splunk.hec.indexName .Values.global.splunk.hec.indexName }}
      index {{ . }}
      {{- end }}
      insecure_ssl {{ or .Values.splunk.hec.insecureSSL .Values.global.splunk.hec.insecureSSL }}
      {{- if or .Values.splunk.hec.clientCert .Values.global.splunk.hec.clientCert }}
      client_cert /fluentd/etc/splunk/hec_client_cert
      {{- end }}
      {{- if or .Values.splunk.hec.clientKey .Values.global.splunk.hec.clientKey }}
      client_key /fluentd/etc/splunk/hec_client_key
      {{- end }}
      {{- if or .Values.splunk.hec.caFile .Values.global.splunk.hec.caFile }}
      ca_file /fluentd/etc/splunk/hec_ca_file
      {{- end }}
      <buffer>
        @type memory
        {{- $limit := .Values.resources.limit }}
        chunk_limit_size {{ if $limit.memory }}{{ template "splunk-kubernetes-objects.convert-memory" $limit.memory }}{{ else }}{{ "200m" }}{{ end }}
        chunk_limit_records 10000
        flush_interval 3s
        retry_max_times 3
      </buffer>
    </match>
