# Default values for splunk-kubernetes-logging.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# = Log Level =
# logLevel is to set log level of the Splunk kubernetes metrics collector. Avaiable values are:
# * debug
# * info
# * warn
# * error
logLevel: "info"


# = Splunk UDP Connection =
splunk:
  # configurations for Splunk UDP input. [REQUIRED]
  udp:
    # hostname / IP of the Splunk instance which has the UDP input enabled.
    host:
    # port of the UDP input
    port:


# = Global Configs =
# allow to use settings for Splunk UDP input from global.
# global settings have lower priority.
global:
  logLevel:
  splunk:
    udp: {}


image:
  tag: v1.5.1
  pullPolicy: IfNotPresent


resources:
  # keep request = limit to keep this container in guaranteed class
  limits:
    cpu: 1
    memory: 200Mi
  requests:
    cpu: 1
    memory: 200Mi


nodeSelector:
  kubernetes.io/role: master


tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"


affinity: {}


service:
  port: 80
  targetPort: 8082
